import type { IconType } from "react-icons";
import {
  FaAirbnb,
  FaAmazon,
  FaApple,
  FaAws,
  FaBehance,
  FaBitbucket,
  FaCodepen,
  FaDigitalOcean,
  FaDiscord,
  FaDocker,
  FaDribbble,
  FaDropbox,
  FaEtsy,
  FaFacebookF,
  FaFigma,
  FaGitlab,
  FaGithub,
  FaGoogle,
  FaGoogleDrive,
  FaInstagram,
  FaLinkedinIn,
  FaLinux,
  FaMastodon,
  FaMedium,
  FaMicrosoft,
  FaPaypal,
  FaPlaystation,
  FaRedditAlien,
  FaShopify,
  FaSlack,
  FaSnapchat,
  FaSpotify,
  FaStackOverflow,
  FaSteam,
  FaStripe,
  FaTelegram,
  FaTiktok,
  FaTwitch,
  FaUbuntu,
  FaWhatsapp,
  FaWikipediaW,
  FaWindows,
  FaXTwitter,
  FaXbox,
  FaYoutube,
} from "react-icons/fa6";
import {
  FiActivity,
  FiArchive,
  FiAtSign,
  FiAward,
  FiBell,
  FiBook,
  FiBox,
  FiBriefcase,
  FiCalendar,
  FiCamera,
  FiCheckCircle,
  FiClipboard,
  FiClock,
  FiCloud,
  FiCode,
  FiCoffee,
  FiCompass,
  FiCpu,
  FiCreditCard,
  FiDatabase,
  FiDollarSign,
  FiEye,
  FiFileText,
  FiFilm,
  FiFlag,
  FiFolder,
  FiGift,
  FiGlobe,
  FiHardDrive,
  FiHeadphones,
  FiHeart,
  FiHexagon,
  FiHome,
  FiImage,
  FiInbox,
  FiInfo,
  FiKey,
  FiLayers,
  FiLink,
  FiLock,
  FiMail,
  FiMapPin,
  FiMessageSquare,
  FiMonitor,
  FiMusic,
  FiPackage,
  FiPenTool,
  FiRss,
  FiSend,
  FiServer,
  FiSettings,
  FiShare2,
  FiShield,
  FiShoppingCart,
  FiSmartphone,
  FiStar,
  FiSun,
  FiTarget,
  FiTerminal,
  FiTool,
  FiTrendingUp,
  FiUpload,
  FiUser,
  FiUsers,
  FiVideo,
  FiWatch,
  FiWifi,
  FiZap,
} from "react-icons/fi";

export interface IconDef {
  key: string;
  label: string;
  Icon: IconType;
  group: "brands" | "general";
}

const ICONS: IconDef[] = [
  // Brands
  make("github", "GitHub", FaGithub, "brands"),
  make("gitlab", "GitLab", FaGitlab, "brands"),
  make("bitbucket", "Bitbucket", FaBitbucket, "brands"),
  make("linkedin", "LinkedIn", FaLinkedinIn, "brands"),
  make("facebook", "Facebook", FaFacebookF, "brands"),
  make("instagram", "Instagram", FaInstagram, "brands"),
  make("x", "X / Twitter", FaXTwitter, "brands"),
  make("discord", "Discord", FaDiscord, "brands"),
  make("slack", "Slack", FaSlack, "brands"),
  make("reddit", "Reddit", FaRedditAlien, "brands"),
  make("youtube", "YouTube", FaYoutube, "brands"),
  make("twitch", "Twitch", FaTwitch, "brands"),
  make("tiktok", "TikTok", FaTiktok, "brands"),
  make("telegram", "Telegram", FaTelegram, "brands"),
  make("whatsapp", "WhatsApp", FaWhatsapp, "brands"),
  make("snapchat", "Snapchat", FaSnapchat, "brands"),
  make("mastodon", "Mastodon", FaMastodon, "brands"),
  make("apple", "Apple", FaApple, "brands"),
  make("google", "Google", FaGoogle, "brands"),
  make("microsoft", "Microsoft", FaMicrosoft, "brands"),
  make("windows", "Windows", FaWindows, "brands"),
  make("linux", "Linux", FaLinux, "brands"),
  make("ubuntu", "Ubuntu", FaUbuntu, "brands"),
  make("aws", "AWS", FaAws, "brands"),
  make("amazon", "Amazon", FaAmazon, "brands"),
  make("digitalocean", "DigitalOcean", FaDigitalOcean, "brands"),
  make("docker", "Docker", FaDocker, "brands"),
  make("figma", "Figma", FaFigma, "brands"),
  make("spotify", "Spotify", FaSpotify, "brands"),
  make("paypal", "PayPal", FaPaypal, "brands"),
  make("stripe", "Stripe", FaStripe, "brands"),
  make("dropbox", "Dropbox", FaDropbox, "brands"),
  make("stackoverflow", "Stack Overflow", FaStackOverflow, "brands"),
  make("dribbble", "Dribbble", FaDribbble, "brands"),
  make("behance", "Behance", FaBehance, "brands"),
  make("medium", "Medium", FaMedium, "brands"),
  make("codepen", "CodePen", FaCodepen, "brands"),
  make("googledrive", "Google Drive", FaGoogleDrive, "brands"),
  make("etsy", "Etsy", FaEtsy, "brands"),
  make("shopify", "Shopify", FaShopify, "brands"),
  make("airbnb", "Airbnb", FaAirbnb, "brands"),
  make("xbox", "Xbox", FaXbox, "brands"),
  make("playstation", "PlayStation", FaPlaystation, "brands"),
  make("steam", "Steam", FaSteam, "brands"),
  make("wikipedia", "Wikipedia", FaWikipediaW, "brands"),

  // General
  make("account", "Account", FiUser, "general"),
  make("team", "Team", FiUsers, "general"),
  make("email", "Email", FiMail, "general"),
  make("server", "Server", FiServer, "general"),
  make("vps", "VPS", FiCpu, "general"),
  make("hardware", "Hardware", FiHardDrive, "general"),
  make("database", "Database", FiDatabase, "general"),
  make("cloud", "Cloud", FiCloud, "general"),
  make("domain", "Domain", FiGlobe, "general"),
  make("wifi", "Wi-Fi", FiWifi, "general"),
  make("key", "Key", FiKey, "general"),
  make("credentials", "Credentials", FiLock, "general"),
  make("security", "Security", FiShield, "general"),
  make("license", "License", FiAward, "general"),
  make("bank", "Bank / Card", FiCreditCard, "general"),
  make("finance", "Finance", FiDollarSign, "general"),
  make("api", "API", FiCode, "general"),
  make("terminal", "Terminal", FiTerminal, "general"),
  make("link", "Link", FiLink, "general"),
  make("home", "Home", FiHome, "general"),
  make("book", "Book", FiBook, "general"),
  make("document", "Document", FiFileText, "general"),
  make("shop", "Shopping", FiShoppingCart, "general"),
  make("camera", "Camera", FiCamera, "general"),
  make("film", "Media", FiFilm, "general"),
  make("music", "Music", FiMusic, "general"),
  make("video", "Video", FiVideo, "general"),
  make("box", "Box", FiBox, "general"),
  make("package", "Package", FiPackage, "general"),
  make("layers", "Layers", FiLayers, "general"),
  make("tools", "Tools", FiPenTool, "general"),
  make("image", "Image", FiImage, "general"),
  make("location", "Location", FiMapPin, "general"),
  make("gift", "Gift", FiGift, "general"),
  make("toolbox", "Toolbox", FiTool, "general"),
  make("hexagon", "Hexagon", FiHexagon, "general"),
  make("settings", "Settings", FiSettings, "general"),
  make("clock", "Time", FiClock, "general"),
  make("star", "Star", FiStar, "general"),
  make("zap", "Energy", FiZap, "general"),
  make("flag", "Flag", FiFlag, "general"),
  make("briefcase", "Work", FiBriefcase, "general"),
  make("coffee", "Coffee", FiCoffee, "general"),
  make("monitor", "Monitor", FiMonitor, "general"),
  make("smartphone", "Mobile", FiSmartphone, "general"),
  make("watch", "Watch", FiWatch, "general"),
  make("archive", "Archive", FiArchive, "general"),
  make("activity", "Activity", FiActivity, "general"),
  make("at", "Username / Handle", FiAtSign, "general"),
  make("bell", "Notifications", FiBell, "general"),
  make("calendar", "Calendar", FiCalendar, "general"),
  make("check", "Check", FiCheckCircle, "general"),
  make("clipboard", "Clipboard", FiClipboard, "general"),
  make("compass", "Compass", FiCompass, "general"),
  make("eye", "View", FiEye, "general"),
  make("folder", "Folder", FiFolder, "general"),
  make("headphones", "Audio", FiHeadphones, "general"),
  make("heart", "Likes", FiHeart, "general"),
  make("inbox", "Inbox", FiInbox, "general"),
  make("message", "Chat", FiMessageSquare, "general"),
  make("send", "Send", FiSend, "general"),
  make("share", "Share", FiShare2, "general"),
  make("sun", "Theme", FiSun, "general"),
  make("target", "Target", FiTarget, "general"),
  make("trend", "Trends", FiTrendingUp, "general"),
  make("upload", "Upload", FiUpload, "general"),
  make("rss", "Feed", FiRss, "general"),
  make("info", "Info", FiInfo, "general"),
];

function make(
  key: string,
  label: string,
  Icon: IconType,
  group: IconDef["group"],
): IconDef {
  return { key, label, Icon, group };
}

const BY_KEY = new Map<string, IconDef>(ICONS.map((def) => [def.key, def]));

export const FALLBACK_ICON: IconDef = {
  key: "box",
  label: "Other",
  Icon: FiBox,
  group: "general",
};

export function getIconDef(key: string | null | undefined): IconDef {
  if (!key) return FALLBACK_ICON;
  return BY_KEY.get(key) ?? FALLBACK_ICON;
}

export function iconDefsByGroup(group: IconDef["group"]): IconDef[] {
  return ICONS.filter((def) => def.group === group);
}

export const ICON_GROUPS = [
  { group: "brands" as const, label: "Brands" },
  { group: "general" as const, label: "General" },
];